title:            Ryo Suzuki
description:      Welcome to Ryo Suzuke\'s Web Page
url:              http://ryooopan.com
signoff:          Ryo Suzuki
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-27423847-3

links:
  - name:         Home
    url:          /
  - name:         Projects
    url:          /projects
  - name:         Research
    url:          /research
  - name:         About
    url:          /about
  - name:         CV/Resume
    url:          /cv.pdf
    external:     true
#   name:         Blog
#   url:          http://ryooopan.com
#   external:     true
#   name:         GitHub
#   url:          http://github.com/ryooopan
#   external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
