title:            Ryo Suzuki - University of Colorado Boulder
description:      Welcome to Ryo Suzuke\'s Home Page
url:              http://ryosuzuki.org
signoff:          Ryo Suzuki
google_analytics: UA-62643728-1

links:
  - name:         Home
    url:          /
  - name:         Projects
    url:          /projects
  - name:         CV/Resume
    url:          /cv/cv.pdf
    external:     true
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
  extensions:
    - smart
