// Generated by CoffeeScript 1.6.3
jQuery(function() {
  $("a[href^='http']:not([href*='" + location.hostname + "'])").attr('target', '_blank');

  return $.each($("[data-time]"), function(index, ele) {
    return $(ele).html(prettyDate(new Date($(this).data("time"))));
  });
});

